version: '3.8'

services:
  frontend:
    container_name: ld-app-frontend
    image: ld-app-frontend
    ports:
      - "80:80"  
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - app-network
    # depends_on:
    #   - backend
    restart: unless-stopped

  backend:
    build: .
    image: ld-app-backend
    ports:
      - "8923:8000"
      - "8443:443"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
    networks:
      - app-network
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local 