"""add size field

Revision ID: 001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None

# 新增configs中是否可见字段
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_configs', sa.Column('visible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_configs', 'visible')
    # ### end Alembic commands ### 